import {
  IDataWithStatus,
  StatusEnum,
  TypesEnum,
} from "./Interfaces/TableCompare";

export const statusColorCompare = {
  [StatusEnum.Created]: "#00FF1A20",
  [StatusEnum.Updated]: "#FFC70040",
  [StatusEnum.Deleted]: "#FF000030",
  [StatusEnum.Reordered]: "#0038FF20",
  NumberOrder: "#0037ffa0",
  [StatusEnum.None]: "none",
  [StatusEnum.Normal]: "none",
};

export const headTableCompare = ["Code", "Name", "Type"];

export const initialDataTableCompare: IDataWithStatus[] = [
  {
    code: "Lec",
    name: "Lecupom",
    type: TypesEnum.PIS,
    status: StatusEnum.Normal,
  },
  {
    code: "Hbo",
    name: "Hbo Max",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "isppremium",
    name: "Portal Assinante",
    type: TypesEnum.PPP,
    status: StatusEnum.Normal,
  },
  {
    code: "test",
    name: "Teste",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test2",
    name: "Teste 2",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test3",
    name: "Teste 3",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test4",
    name: "Teste 4",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test5",
    name: "Teste 5",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test7",
    name: "Teste 7",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test8",
    name: "Teste 8",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test9",
    name: "Teste 9",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test10",
    name: "Teste 10",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test11",
    name: "Teste 11",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test12",
    name: "Teste 12",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test13",
    name: "Teste 13",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test14",
    name: "Teste 14",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test15",
    name: "Teste 15",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test16",
    name: "Teste 16",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test17",
    name: "Teste 17",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test18",
    name: "Teste 18",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test19",
    name: "Teste 19",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test20",
    name: "Teste 20",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test21",
    name: "Teste 21",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test22",
    name: "Teste 22",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test23",
    name: "Teste 23",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test24",
    name: "Teste 24",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test25",
    name: "Teste 25",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test26",
    name: "Teste 26",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test27",
    name: "Teste 27",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test28",
    name: "Teste 28",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test29",
    name: "Teste 29",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test30",
    name: "Teste 30",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
];

export const initialNewDataTableCompare: IDataWithStatus[] = [
  {
    code: "novo 1",
    name: "Novo 1",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "Lec",
    name: "Lecupom",
    type: TypesEnum.PIS,
    status: StatusEnum.Normal,
  },
  {
    code: "Hbo",
    name: "Hbo Max",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "isppremium",
    name: "Portal Assinante",
    type: TypesEnum.PPP,
    status: StatusEnum.Normal,
  },
  {
    code: "test",
    name: "Teste",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test2",
    name: "Teste 2",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test3",
    name: "Teste 3",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test4",
    name: "Teste 4",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test5",
    name: "Teste 5",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test7",
    name: "Teste 7",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test19",
    name: "Teste 19",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test8",
    name: "Teste 8",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test9",
    name: "Teste 9",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test10",
    name: "Teste 10",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test11",
    name: "Teste 11",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test12",
    name: "Teste 12",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test13",
    name: "Teste 13",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test14",
    name: "Teste 14",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test15",
    name: "Teste 15",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test16",
    name: "Teste 16",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test17",
    name: "Teste 17",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test18",
    name: "Teste 18",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test20",
    name: "Teste 20",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test21",
    name: "Teste 21",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test22",
    name: "Teste 22",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test23",
    name: "Teste 23",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  //   {
  //     code: "test24",
  //     name: "Teste 24",
  //     type: TypesEnum.PPA,
  //     status: StatusEnum.Normal,
  //   },
  {
    code: "test25",
    name: "Teste 25",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test26",
    name: "Teste 26",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test27",
    name: "Teste 27",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test28",
    name: "Teste 28",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
  {
    code: "test29",
    name: "Teste 29",
    type: TypesEnum.PIS,
    status: StatusEnum.Normal,
  },
  {
    code: "test30",
    name: "Teste 30",
    type: TypesEnum.PPA,
    status: StatusEnum.Normal,
  },
];
